### ISSUE TITLE
Do you mind if I continue to develop this project

### ISSUE THREAD

**Issue by alphaadsda** [Utrit/GravProject#1]
This is a commendable and fantastic idea. I'm a huge fan of the Portal series. Would you mind if I continued developing this project? I plan to submit my subsequent developments here, acknowledging your original idea and providing a link to your GitHub repository. I eagerly await your response.

**Comment by Utrit** [comment]
Greetings, I'm glad for the interest in my idea, I have plans to rework the code part of the game to add mechanics etc, but have not gotten around to it yet. You are free to modify and use my work, I would be happy to see what you get out of it.
